### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by PandaZhym** [emacs-eaf/eaf-jupyter#4]
when i type M-x eaf-open-jupyter, then in the minibuffer, it is displaying: [EAF/jupyter] Please install qtconsole first.
however, i have installed the package!
i type this in my Emacs's shell---pip list
then it tells me that i have installed qtconsole and its version is 5.0.2
what can i do for making this work?

**Comment by manateelazycat** [comment]
use install-eaf.py install depends

**Comment by PandaZhym** [comment]
I had used this file(in the terminal i typed this: ./install-eaf.py), but it didn't work anyway.

**Comment by bensetel** [comment]
I am having this problem as well (on OS X)
